// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrixmul.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrixmul::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrixmul::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> matrixmul::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<5> matrixmul::ap_ST_fsm_pp0_stage1 = "10";
const sc_lv<5> matrixmul::ap_ST_fsm_pp0_stage2 = "100";
const sc_lv<5> matrixmul::ap_ST_fsm_pp0_stage3 = "1000";
const sc_lv<5> matrixmul::ap_ST_fsm_pp0_stage4 = "10000";
const sc_lv<32> matrixmul::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool matrixmul::ap_const_boolean_1 = true;
const sc_lv<32> matrixmul::ap_const_lv32_4 = "100";
const bool matrixmul::ap_const_boolean_0 = false;
const sc_lv<32> matrixmul::ap_const_lv32_1 = "1";
const sc_lv<32> matrixmul::ap_const_lv32_2 = "10";
const sc_lv<32> matrixmul::ap_const_lv32_3 = "11";
const sc_lv<64> matrixmul::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> matrixmul::ap_const_lv64_1 = "1";
const sc_lv<64> matrixmul::ap_const_lv64_2 = "10";
const sc_lv<64> matrixmul::ap_const_lv64_3 = "11";
const sc_lv<64> matrixmul::ap_const_lv64_4 = "100";
const sc_lv<64> matrixmul::ap_const_lv64_5 = "101";
const sc_lv<64> matrixmul::ap_const_lv64_6 = "110";
const sc_lv<64> matrixmul::ap_const_lv64_7 = "111";
const sc_lv<64> matrixmul::ap_const_lv64_8 = "1000";
const sc_lv<32> matrixmul::ap_const_lv32_8 = "1000";
const sc_lv<32> matrixmul::ap_const_lv32_F = "1111";
const sc_lv<32> matrixmul::ap_const_lv32_10 = "10000";
const sc_lv<32> matrixmul::ap_const_lv32_17 = "10111";

matrixmul::matrixmul(sc_module_name name) : sc_module(name), mVcdFile(0) {
    matrixmul_mac_mulbkb_U1 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U1");
    matrixmul_mac_mulbkb_U1->din0(trunc_ln60_1_fu_268_p1);
    matrixmul_mac_mulbkb_U1->din1(grp_fu_434_p1);
    matrixmul_mac_mulbkb_U1->din2(grp_fu_434_p2);
    matrixmul_mac_mulbkb_U1->dout(grp_fu_434_p3);
    matrixmul_mac_mulbkb_U2 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U2");
    matrixmul_mac_mulbkb_U2->din0(trunc_ln60_2_fu_290_p1);
    matrixmul_mac_mulbkb_U2->din1(grp_fu_442_p1);
    matrixmul_mac_mulbkb_U2->din2(grp_fu_442_p2);
    matrixmul_mac_mulbkb_U2->dout(grp_fu_442_p3);
    matrixmul_mac_mulcud_U3 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U3");
    matrixmul_mac_mulcud_U3->din0(reg_256);
    matrixmul_mac_mulcud_U3->din1(grp_fu_450_p1);
    matrixmul_mac_mulcud_U3->din2(add_ln60_reg_601);
    matrixmul_mac_mulcud_U3->dout(grp_fu_450_p3);
    matrixmul_mac_mulcud_U4 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U4");
    matrixmul_mac_mulcud_U4->din0(tmp_7_reg_612);
    matrixmul_mac_mulcud_U4->din1(grp_fu_458_p1);
    matrixmul_mac_mulcud_U4->din2(add_ln60_2_reg_623);
    matrixmul_mac_mulcud_U4->dout(grp_fu_458_p3);
    matrixmul_mac_mulbkb_U5 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U5");
    matrixmul_mac_mulbkb_U5->din0(trunc_ln60_3_fu_363_p1);
    matrixmul_mac_mulbkb_U5->din1(grp_fu_466_p1);
    matrixmul_mac_mulbkb_U5->din2(grp_fu_466_p2);
    matrixmul_mac_mulbkb_U5->dout(grp_fu_466_p3);
    matrixmul_mac_mulbkb_U6 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U6");
    matrixmul_mac_mulbkb_U6->din0(grp_fu_473_p0);
    matrixmul_mac_mulbkb_U6->din1(trunc_ln60_4_reg_633);
    matrixmul_mac_mulbkb_U6->din2(grp_fu_473_p2);
    matrixmul_mac_mulbkb_U6->dout(grp_fu_473_p3);
    matrixmul_mac_mulcud_U7 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U7");
    matrixmul_mac_mulcud_U7->din0(reg_256);
    matrixmul_mac_mulcud_U7->din1(grp_fu_480_p1);
    matrixmul_mac_mulcud_U7->din2(add_ln60_4_reg_682);
    matrixmul_mac_mulcud_U7->dout(grp_fu_480_p3);
    matrixmul_mac_mulcud_U8 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U8");
    matrixmul_mac_mulcud_U8->din0(grp_fu_487_p0);
    matrixmul_mac_mulcud_U8->din1(tmp_6_reg_638);
    matrixmul_mac_mulcud_U8->din2(add_ln60_6_reg_699);
    matrixmul_mac_mulcud_U8->dout(grp_fu_487_p3);
    matrixmul_mac_mulbkb_U9 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U9");
    matrixmul_mac_mulbkb_U9->din0(grp_fu_494_p0);
    matrixmul_mac_mulbkb_U9->din1(grp_fu_494_p1);
    matrixmul_mac_mulbkb_U9->din2(grp_fu_494_p2);
    matrixmul_mac_mulbkb_U9->dout(grp_fu_494_p3);
    matrixmul_mac_mulbkb_U10 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U10");
    matrixmul_mac_mulbkb_U10->din0(grp_fu_500_p0);
    matrixmul_mac_mulbkb_U10->din1(grp_fu_500_p1);
    matrixmul_mac_mulbkb_U10->din2(grp_fu_500_p2);
    matrixmul_mac_mulbkb_U10->dout(grp_fu_500_p3);
    matrixmul_mac_mulcud_U11 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U11");
    matrixmul_mac_mulcud_U11->din0(grp_fu_506_p0);
    matrixmul_mac_mulcud_U11->din1(grp_fu_506_p1);
    matrixmul_mac_mulcud_U11->din2(add_ln60_8_reg_726);
    matrixmul_mac_mulcud_U11->dout(grp_fu_506_p3);
    matrixmul_mac_mulcud_U12 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U12");
    matrixmul_mac_mulcud_U12->din0(grp_fu_512_p0);
    matrixmul_mac_mulcud_U12->din1(grp_fu_512_p1);
    matrixmul_mac_mulcud_U12->din2(add_ln60_10_reg_731);
    matrixmul_mac_mulcud_U12->dout(grp_fu_512_p3);
    matrixmul_mac_mulbkb_U13 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U13");
    matrixmul_mac_mulbkb_U13->din0(grp_fu_518_p0);
    matrixmul_mac_mulbkb_U13->din1(grp_fu_518_p1);
    matrixmul_mac_mulbkb_U13->din2(grp_fu_518_p2);
    matrixmul_mac_mulbkb_U13->dout(grp_fu_518_p3);
    matrixmul_mac_mulbkb_U14 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U14");
    matrixmul_mac_mulbkb_U14->din0(grp_fu_525_p0);
    matrixmul_mac_mulbkb_U14->din1(grp_fu_525_p1);
    matrixmul_mac_mulbkb_U14->din2(grp_fu_525_p2);
    matrixmul_mac_mulbkb_U14->dout(grp_fu_525_p3);
    matrixmul_mac_mulcud_U15 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U15");
    matrixmul_mac_mulcud_U15->din0(grp_fu_532_p0);
    matrixmul_mac_mulcud_U15->din1(grp_fu_532_p1);
    matrixmul_mac_mulcud_U15->din2(add_ln60_12_reg_746);
    matrixmul_mac_mulcud_U15->dout(grp_fu_532_p3);
    matrixmul_mac_mulcud_U16 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U16");
    matrixmul_mac_mulcud_U16->din0(grp_fu_539_p0);
    matrixmul_mac_mulcud_U16->din1(grp_fu_539_p1);
    matrixmul_mac_mulcud_U16->din2(add_ln60_14_reg_751);
    matrixmul_mac_mulcud_U16->dout(grp_fu_539_p3);
    matrixmul_mac_mulbkb_U17 = new matrixmul_mac_mulbkb<1,1,8,8,16,16>("matrixmul_mac_mulbkb_U17");
    matrixmul_mac_mulbkb_U17->din0(grp_fu_546_p0);
    matrixmul_mac_mulbkb_U17->din1(grp_fu_546_p1);
    matrixmul_mac_mulbkb_U17->din2(grp_fu_546_p2);
    matrixmul_mac_mulbkb_U17->dout(grp_fu_546_p3);
    matrixmul_mac_mulcud_U18 = new matrixmul_mac_mulcud<1,1,8,8,16,16>("matrixmul_mac_mulcud_U18");
    matrixmul_mac_mulcud_U18->din0(grp_fu_552_p0);
    matrixmul_mac_mulcud_U18->din1(grp_fu_552_p1);
    matrixmul_mac_mulcud_U18->din2(grp_fu_546_p3);
    matrixmul_mac_mulcud_U18->dout(grp_fu_552_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_a_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_a_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);

    SC_METHOD(thread_ap_block_pp0_stage4);

    SC_METHOD(thread_ap_block_pp0_stage4_11001);

    SC_METHOD(thread_ap_block_pp0_stage4_subdone);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage4_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state7_pp0_stage1_iter1);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0_reg );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp0_0to0);
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_idle_pp0_1to1);
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to0 );

    SC_METHOD(thread_b_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_b_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_b_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_b_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_232_p4);
    sensitive << ( a_q0 );

    SC_METHOD(thread_grp_fu_242_p4);
    sensitive << ( b_q0 );

    SC_METHOD(thread_grp_fu_434_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( sext_ln60_fu_264_p1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_grp_fu_434_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( mul_ln60_2_fu_284_p0 );
    sensitive << ( mul_ln60_2_fu_284_p1 );

    SC_METHOD(thread_grp_fu_442_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( sext_ln60_fu_264_p1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_grp_fu_442_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( mul_ln60_5_fu_322_p0 );
    sensitive << ( mul_ln60_5_fu_322_p1 );

    SC_METHOD(thread_grp_fu_450_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( sext_ln60_2_fu_352_p1 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_458_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( sext_ln60_2_fu_352_p1 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_466_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( sext_ln60_reg_579 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_466_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( mul_ln60_8_fu_375_p0 );
    sensitive << ( mul_ln60_8_fu_375_p1 );

    SC_METHOD(thread_grp_fu_473_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( sext_ln60_1_reg_584 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_473_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( mul_ln60_11_fu_386_p0 );
    sensitive << ( mul_ln60_11_fu_386_p1 );

    SC_METHOD(thread_grp_fu_480_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_2_reg_653 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_grp_fu_487_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_3_reg_658 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_grp_fu_494_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_6_reg_606 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_grp_fu_494_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_12_reg_687 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_grp_fu_494_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( mul_ln60_14_fu_402_p0 );
    sensitive << ( mul_ln60_14_fu_402_p1 );

    SC_METHOD(thread_grp_fu_500_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_9_reg_670 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_grp_fu_500_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_12_reg_687 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_grp_fu_500_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( mul_ln60_17_fu_406_p0 );
    sensitive << ( mul_ln60_17_fu_406_p1 );

    SC_METHOD(thread_grp_fu_506_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_7_reg_664 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_506_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_13_reg_720 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_512_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_10_reg_714 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_512_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_13_reg_720 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_518_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_1_reg_584 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_518_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_15_fu_410_p1 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_518_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4 );
    sensitive << ( mul_ln60_20_fu_416_p0 );
    sensitive << ( mul_ln60_20_fu_416_p1 );

    SC_METHOD(thread_grp_fu_525_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_6_reg_606 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_525_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_15_fu_410_p1 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_525_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4 );
    sensitive << ( mul_ln60_23_fu_421_p0 );
    sensitive << ( mul_ln60_23_fu_421_p1 );

    SC_METHOD(thread_grp_fu_532_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln60_3_reg_658 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_532_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln60_16_fu_426_p1 );

    SC_METHOD(thread_grp_fu_539_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln60_7_reg_664 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_539_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln60_16_fu_426_p1 );

    SC_METHOD(thread_grp_fu_546_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln60_9_reg_670 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_546_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln60_15_reg_736 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_546_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( mul_ln60_26_fu_430_p0 );
    sensitive << ( mul_ln60_26_fu_430_p1 );

    SC_METHOD(thread_grp_fu_552_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln60_10_reg_714 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_552_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln60_16_fu_426_p1 );

    SC_METHOD(thread_mul_ln60_11_fu_386_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( sext_ln60_5_reg_595 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_mul_ln60_11_fu_386_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( tmp_9_reg_643 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_mul_ln60_14_fu_402_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_8_reg_617 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_mul_ln60_14_fu_402_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_14_reg_693 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_mul_ln60_17_fu_406_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_11_reg_676 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_mul_ln60_17_fu_406_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sext_ln60_14_reg_693 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_mul_ln60_20_fu_416_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_5_reg_595 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_mul_ln60_20_fu_416_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_17_fu_413_p1 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_mul_ln60_23_fu_421_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_8_reg_617 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_mul_ln60_23_fu_421_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( sext_ln60_17_fu_413_p1 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_mul_ln60_26_fu_430_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln60_11_reg_676 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln60_26_fu_430_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sext_ln60_17_reg_741 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln60_2_fu_284_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( grp_fu_242_p4 );

    SC_METHOD(thread_mul_ln60_2_fu_284_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( sext_ln60_4_fu_276_p1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_mul_ln60_5_fu_322_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_8_fu_308_p4 );

    SC_METHOD(thread_mul_ln60_5_fu_322_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( sext_ln60_4_fu_276_p1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_mul_ln60_8_fu_375_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( grp_fu_242_p4 );

    SC_METHOD(thread_mul_ln60_8_fu_375_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( sext_ln60_4_reg_590 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_res_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_res_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_res_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_res_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_res_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( add_ln60_17_reg_756 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );
    sensitive << ( grp_fu_458_p3 );
    sensitive << ( grp_fu_487_p3 );
    sensitive << ( grp_fu_512_p3 );
    sensitive << ( grp_fu_532_p3 );

    SC_METHOD(thread_res_d1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );
    sensitive << ( grp_fu_450_p3 );
    sensitive << ( grp_fu_480_p3 );
    sensitive << ( grp_fu_506_p3 );
    sensitive << ( grp_fu_539_p3 );

    SC_METHOD(thread_res_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_res_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_sext_ln60_10_fu_395_p1);
    sensitive << ( reg_256 );

    SC_METHOD(thread_sext_ln60_11_fu_371_p1);
    sensitive << ( grp_fu_242_p4 );

    SC_METHOD(thread_sext_ln60_12_fu_380_p1);
    sensitive << ( trunc_ln60_4_reg_633 );

    SC_METHOD(thread_sext_ln60_13_fu_399_p1);
    sensitive << ( tmp_6_reg_638 );

    SC_METHOD(thread_sext_ln60_14_fu_383_p1);
    sensitive << ( tmp_9_reg_643 );

    SC_METHOD(thread_sext_ln60_15_fu_410_p1);
    sensitive << ( trunc_ln60_5_reg_704 );

    SC_METHOD(thread_sext_ln60_16_fu_426_p1);
    sensitive << ( reg_252 );

    SC_METHOD(thread_sext_ln60_17_fu_413_p1);
    sensitive << ( tmp_11_reg_709 );

    SC_METHOD(thread_sext_ln60_1_fu_272_p1);
    sensitive << ( trunc_ln60_1_fu_268_p1 );

    SC_METHOD(thread_sext_ln60_2_fu_352_p1);
    sensitive << ( reg_252 );

    SC_METHOD(thread_sext_ln60_3_fu_356_p1);
    sensitive << ( reg_256 );

    SC_METHOD(thread_sext_ln60_4_fu_276_p1);
    sensitive << ( grp_fu_232_p4 );

    SC_METHOD(thread_sext_ln60_5_fu_280_p1);
    sensitive << ( grp_fu_242_p4 );

    SC_METHOD(thread_sext_ln60_6_fu_294_p1);
    sensitive << ( trunc_ln60_2_fu_290_p1 );

    SC_METHOD(thread_sext_ln60_7_fu_360_p1);
    sensitive << ( tmp_7_reg_612 );

    SC_METHOD(thread_sext_ln60_8_fu_318_p1);
    sensitive << ( tmp_8_fu_308_p4 );

    SC_METHOD(thread_sext_ln60_9_fu_367_p1);
    sensitive << ( trunc_ln60_3_fu_363_p1 );

    SC_METHOD(thread_sext_ln60_fu_264_p1);
    sensitive << ( trunc_ln60_fu_260_p1 );

    SC_METHOD(thread_tmp_8_fu_308_p4);
    sensitive << ( b_q1 );

    SC_METHOD(thread_trunc_ln60_1_fu_268_p1);
    sensitive << ( b_q0 );

    SC_METHOD(thread_trunc_ln60_2_fu_290_p1);
    sensitive << ( b_q1 );

    SC_METHOD(thread_trunc_ln60_3_fu_363_p1);
    sensitive << ( b_q0 );

    SC_METHOD(thread_trunc_ln60_4_fu_328_p1);
    sensitive << ( a_q1 );

    SC_METHOD(thread_trunc_ln60_5_fu_391_p1);
    sensitive << ( a_q0 );

    SC_METHOD(thread_trunc_ln60_fu_260_p1);
    sensitive << ( a_q0 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage4_subdone );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_idle_pp0_1to1 );
    sensitive << ( ap_reset_idle_pp0 );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrixmul_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, a_address1, "(port)a_address1");
    sc_trace(mVcdFile, a_ce1, "(port)a_ce1");
    sc_trace(mVcdFile, a_q1, "(port)a_q1");
    sc_trace(mVcdFile, b_address0, "(port)b_address0");
    sc_trace(mVcdFile, b_ce0, "(port)b_ce0");
    sc_trace(mVcdFile, b_q0, "(port)b_q0");
    sc_trace(mVcdFile, b_address1, "(port)b_address1");
    sc_trace(mVcdFile, b_ce1, "(port)b_ce1");
    sc_trace(mVcdFile, b_q1, "(port)b_q1");
    sc_trace(mVcdFile, res_address0, "(port)res_address0");
    sc_trace(mVcdFile, res_ce0, "(port)res_ce0");
    sc_trace(mVcdFile, res_we0, "(port)res_we0");
    sc_trace(mVcdFile, res_d0, "(port)res_d0");
    sc_trace(mVcdFile, res_address1, "(port)res_address1");
    sc_trace(mVcdFile, res_ce1, "(port)res_ce1");
    sc_trace(mVcdFile, res_we1, "(port)res_we1");
    sc_trace(mVcdFile, res_d1, "(port)res_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage4, "ap_CS_fsm_pp0_stage4");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage4_iter0, "ap_block_state5_pp0_stage4_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage4_11001, "ap_block_pp0_stage4_11001");
    sc_trace(mVcdFile, reg_252, "reg_252");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage1_iter0, "ap_block_state2_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage1_iter1, "ap_block_state7_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage2_iter0, "ap_block_state3_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, reg_256, "reg_256");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, sext_ln60_fu_264_p1, "sext_ln60_fu_264_p1");
    sc_trace(mVcdFile, sext_ln60_reg_579, "sext_ln60_reg_579");
    sc_trace(mVcdFile, sext_ln60_1_fu_272_p1, "sext_ln60_1_fu_272_p1");
    sc_trace(mVcdFile, sext_ln60_1_reg_584, "sext_ln60_1_reg_584");
    sc_trace(mVcdFile, sext_ln60_4_fu_276_p1, "sext_ln60_4_fu_276_p1");
    sc_trace(mVcdFile, sext_ln60_4_reg_590, "sext_ln60_4_reg_590");
    sc_trace(mVcdFile, sext_ln60_5_fu_280_p1, "sext_ln60_5_fu_280_p1");
    sc_trace(mVcdFile, sext_ln60_5_reg_595, "sext_ln60_5_reg_595");
    sc_trace(mVcdFile, grp_fu_434_p3, "grp_fu_434_p3");
    sc_trace(mVcdFile, add_ln60_reg_601, "add_ln60_reg_601");
    sc_trace(mVcdFile, sext_ln60_6_fu_294_p1, "sext_ln60_6_fu_294_p1");
    sc_trace(mVcdFile, sext_ln60_6_reg_606, "sext_ln60_6_reg_606");
    sc_trace(mVcdFile, tmp_7_reg_612, "tmp_7_reg_612");
    sc_trace(mVcdFile, sext_ln60_8_fu_318_p1, "sext_ln60_8_fu_318_p1");
    sc_trace(mVcdFile, sext_ln60_8_reg_617, "sext_ln60_8_reg_617");
    sc_trace(mVcdFile, grp_fu_442_p3, "grp_fu_442_p3");
    sc_trace(mVcdFile, add_ln60_2_reg_623, "add_ln60_2_reg_623");
    sc_trace(mVcdFile, trunc_ln60_4_fu_328_p1, "trunc_ln60_4_fu_328_p1");
    sc_trace(mVcdFile, trunc_ln60_4_reg_633, "trunc_ln60_4_reg_633");
    sc_trace(mVcdFile, tmp_6_reg_638, "tmp_6_reg_638");
    sc_trace(mVcdFile, tmp_9_reg_643, "tmp_9_reg_643");
    sc_trace(mVcdFile, sext_ln60_2_fu_352_p1, "sext_ln60_2_fu_352_p1");
    sc_trace(mVcdFile, sext_ln60_2_reg_653, "sext_ln60_2_reg_653");
    sc_trace(mVcdFile, sext_ln60_3_fu_356_p1, "sext_ln60_3_fu_356_p1");
    sc_trace(mVcdFile, sext_ln60_3_reg_658, "sext_ln60_3_reg_658");
    sc_trace(mVcdFile, sext_ln60_7_fu_360_p1, "sext_ln60_7_fu_360_p1");
    sc_trace(mVcdFile, sext_ln60_7_reg_664, "sext_ln60_7_reg_664");
    sc_trace(mVcdFile, sext_ln60_9_fu_367_p1, "sext_ln60_9_fu_367_p1");
    sc_trace(mVcdFile, sext_ln60_9_reg_670, "sext_ln60_9_reg_670");
    sc_trace(mVcdFile, sext_ln60_11_fu_371_p1, "sext_ln60_11_fu_371_p1");
    sc_trace(mVcdFile, sext_ln60_11_reg_676, "sext_ln60_11_reg_676");
    sc_trace(mVcdFile, grp_fu_466_p3, "grp_fu_466_p3");
    sc_trace(mVcdFile, add_ln60_4_reg_682, "add_ln60_4_reg_682");
    sc_trace(mVcdFile, sext_ln60_12_fu_380_p1, "sext_ln60_12_fu_380_p1");
    sc_trace(mVcdFile, sext_ln60_12_reg_687, "sext_ln60_12_reg_687");
    sc_trace(mVcdFile, sext_ln60_14_fu_383_p1, "sext_ln60_14_fu_383_p1");
    sc_trace(mVcdFile, sext_ln60_14_reg_693, "sext_ln60_14_reg_693");
    sc_trace(mVcdFile, grp_fu_473_p3, "grp_fu_473_p3");
    sc_trace(mVcdFile, add_ln60_6_reg_699, "add_ln60_6_reg_699");
    sc_trace(mVcdFile, trunc_ln60_5_fu_391_p1, "trunc_ln60_5_fu_391_p1");
    sc_trace(mVcdFile, trunc_ln60_5_reg_704, "trunc_ln60_5_reg_704");
    sc_trace(mVcdFile, grp_fu_232_p4, "grp_fu_232_p4");
    sc_trace(mVcdFile, tmp_11_reg_709, "tmp_11_reg_709");
    sc_trace(mVcdFile, sext_ln60_10_fu_395_p1, "sext_ln60_10_fu_395_p1");
    sc_trace(mVcdFile, sext_ln60_10_reg_714, "sext_ln60_10_reg_714");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage3_iter0, "ap_block_state4_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, sext_ln60_13_fu_399_p1, "sext_ln60_13_fu_399_p1");
    sc_trace(mVcdFile, sext_ln60_13_reg_720, "sext_ln60_13_reg_720");
    sc_trace(mVcdFile, grp_fu_494_p3, "grp_fu_494_p3");
    sc_trace(mVcdFile, add_ln60_8_reg_726, "add_ln60_8_reg_726");
    sc_trace(mVcdFile, grp_fu_500_p3, "grp_fu_500_p3");
    sc_trace(mVcdFile, add_ln60_10_reg_731, "add_ln60_10_reg_731");
    sc_trace(mVcdFile, sext_ln60_15_fu_410_p1, "sext_ln60_15_fu_410_p1");
    sc_trace(mVcdFile, sext_ln60_15_reg_736, "sext_ln60_15_reg_736");
    sc_trace(mVcdFile, sext_ln60_17_fu_413_p1, "sext_ln60_17_fu_413_p1");
    sc_trace(mVcdFile, sext_ln60_17_reg_741, "sext_ln60_17_reg_741");
    sc_trace(mVcdFile, grp_fu_518_p3, "grp_fu_518_p3");
    sc_trace(mVcdFile, add_ln60_12_reg_746, "add_ln60_12_reg_746");
    sc_trace(mVcdFile, grp_fu_525_p3, "grp_fu_525_p3");
    sc_trace(mVcdFile, add_ln60_14_reg_751, "add_ln60_14_reg_751");
    sc_trace(mVcdFile, grp_fu_552_p3, "grp_fu_552_p3");
    sc_trace(mVcdFile, add_ln60_17_reg_756, "add_ln60_17_reg_756");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0_reg, "ap_enable_reg_pp0_iter0_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage4_subdone, "ap_block_pp0_stage4_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, ap_block_pp0_stage4, "ap_block_pp0_stage4");
    sc_trace(mVcdFile, grp_fu_450_p3, "grp_fu_450_p3");
    sc_trace(mVcdFile, grp_fu_458_p3, "grp_fu_458_p3");
    sc_trace(mVcdFile, grp_fu_480_p3, "grp_fu_480_p3");
    sc_trace(mVcdFile, grp_fu_487_p3, "grp_fu_487_p3");
    sc_trace(mVcdFile, grp_fu_506_p3, "grp_fu_506_p3");
    sc_trace(mVcdFile, grp_fu_512_p3, "grp_fu_512_p3");
    sc_trace(mVcdFile, grp_fu_532_p3, "grp_fu_532_p3");
    sc_trace(mVcdFile, grp_fu_539_p3, "grp_fu_539_p3");
    sc_trace(mVcdFile, trunc_ln60_fu_260_p1, "trunc_ln60_fu_260_p1");
    sc_trace(mVcdFile, trunc_ln60_1_fu_268_p1, "trunc_ln60_1_fu_268_p1");
    sc_trace(mVcdFile, grp_fu_242_p4, "grp_fu_242_p4");
    sc_trace(mVcdFile, mul_ln60_2_fu_284_p0, "mul_ln60_2_fu_284_p0");
    sc_trace(mVcdFile, mul_ln60_2_fu_284_p1, "mul_ln60_2_fu_284_p1");
    sc_trace(mVcdFile, trunc_ln60_2_fu_290_p1, "trunc_ln60_2_fu_290_p1");
    sc_trace(mVcdFile, tmp_8_fu_308_p4, "tmp_8_fu_308_p4");
    sc_trace(mVcdFile, mul_ln60_5_fu_322_p0, "mul_ln60_5_fu_322_p0");
    sc_trace(mVcdFile, mul_ln60_5_fu_322_p1, "mul_ln60_5_fu_322_p1");
    sc_trace(mVcdFile, trunc_ln60_3_fu_363_p1, "trunc_ln60_3_fu_363_p1");
    sc_trace(mVcdFile, mul_ln60_8_fu_375_p0, "mul_ln60_8_fu_375_p0");
    sc_trace(mVcdFile, mul_ln60_8_fu_375_p1, "mul_ln60_8_fu_375_p1");
    sc_trace(mVcdFile, mul_ln60_11_fu_386_p0, "mul_ln60_11_fu_386_p0");
    sc_trace(mVcdFile, mul_ln60_11_fu_386_p1, "mul_ln60_11_fu_386_p1");
    sc_trace(mVcdFile, mul_ln60_14_fu_402_p0, "mul_ln60_14_fu_402_p0");
    sc_trace(mVcdFile, mul_ln60_14_fu_402_p1, "mul_ln60_14_fu_402_p1");
    sc_trace(mVcdFile, mul_ln60_17_fu_406_p0, "mul_ln60_17_fu_406_p0");
    sc_trace(mVcdFile, mul_ln60_17_fu_406_p1, "mul_ln60_17_fu_406_p1");
    sc_trace(mVcdFile, mul_ln60_20_fu_416_p0, "mul_ln60_20_fu_416_p0");
    sc_trace(mVcdFile, mul_ln60_20_fu_416_p1, "mul_ln60_20_fu_416_p1");
    sc_trace(mVcdFile, mul_ln60_23_fu_421_p0, "mul_ln60_23_fu_421_p0");
    sc_trace(mVcdFile, mul_ln60_23_fu_421_p1, "mul_ln60_23_fu_421_p1");
    sc_trace(mVcdFile, mul_ln60_26_fu_430_p0, "mul_ln60_26_fu_430_p0");
    sc_trace(mVcdFile, mul_ln60_26_fu_430_p1, "mul_ln60_26_fu_430_p1");
    sc_trace(mVcdFile, grp_fu_434_p1, "grp_fu_434_p1");
    sc_trace(mVcdFile, grp_fu_434_p2, "grp_fu_434_p2");
    sc_trace(mVcdFile, grp_fu_442_p1, "grp_fu_442_p1");
    sc_trace(mVcdFile, grp_fu_442_p2, "grp_fu_442_p2");
    sc_trace(mVcdFile, grp_fu_450_p1, "grp_fu_450_p1");
    sc_trace(mVcdFile, grp_fu_458_p1, "grp_fu_458_p1");
    sc_trace(mVcdFile, grp_fu_466_p1, "grp_fu_466_p1");
    sc_trace(mVcdFile, grp_fu_466_p2, "grp_fu_466_p2");
    sc_trace(mVcdFile, grp_fu_473_p0, "grp_fu_473_p0");
    sc_trace(mVcdFile, grp_fu_473_p2, "grp_fu_473_p2");
    sc_trace(mVcdFile, grp_fu_480_p1, "grp_fu_480_p1");
    sc_trace(mVcdFile, grp_fu_487_p0, "grp_fu_487_p0");
    sc_trace(mVcdFile, grp_fu_494_p0, "grp_fu_494_p0");
    sc_trace(mVcdFile, grp_fu_494_p1, "grp_fu_494_p1");
    sc_trace(mVcdFile, grp_fu_494_p2, "grp_fu_494_p2");
    sc_trace(mVcdFile, grp_fu_500_p0, "grp_fu_500_p0");
    sc_trace(mVcdFile, grp_fu_500_p1, "grp_fu_500_p1");
    sc_trace(mVcdFile, grp_fu_500_p2, "grp_fu_500_p2");
    sc_trace(mVcdFile, grp_fu_506_p0, "grp_fu_506_p0");
    sc_trace(mVcdFile, grp_fu_506_p1, "grp_fu_506_p1");
    sc_trace(mVcdFile, grp_fu_512_p0, "grp_fu_512_p0");
    sc_trace(mVcdFile, grp_fu_512_p1, "grp_fu_512_p1");
    sc_trace(mVcdFile, grp_fu_518_p0, "grp_fu_518_p0");
    sc_trace(mVcdFile, grp_fu_518_p1, "grp_fu_518_p1");
    sc_trace(mVcdFile, grp_fu_518_p2, "grp_fu_518_p2");
    sc_trace(mVcdFile, grp_fu_525_p0, "grp_fu_525_p0");
    sc_trace(mVcdFile, grp_fu_525_p1, "grp_fu_525_p1");
    sc_trace(mVcdFile, grp_fu_525_p2, "grp_fu_525_p2");
    sc_trace(mVcdFile, grp_fu_532_p0, "grp_fu_532_p0");
    sc_trace(mVcdFile, grp_fu_532_p1, "grp_fu_532_p1");
    sc_trace(mVcdFile, sext_ln60_16_fu_426_p1, "sext_ln60_16_fu_426_p1");
    sc_trace(mVcdFile, grp_fu_539_p0, "grp_fu_539_p0");
    sc_trace(mVcdFile, grp_fu_539_p1, "grp_fu_539_p1");
    sc_trace(mVcdFile, grp_fu_546_p0, "grp_fu_546_p0");
    sc_trace(mVcdFile, grp_fu_546_p1, "grp_fu_546_p1");
    sc_trace(mVcdFile, grp_fu_546_p2, "grp_fu_546_p2");
    sc_trace(mVcdFile, grp_fu_552_p0, "grp_fu_552_p0");
    sc_trace(mVcdFile, grp_fu_552_p1, "grp_fu_552_p1");
    sc_trace(mVcdFile, grp_fu_546_p3, "grp_fu_546_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_idle_pp0_1to1, "ap_idle_pp0_1to1");
    sc_trace(mVcdFile, ap_idle_pp0_0to0, "ap_idle_pp0_0to0");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
    mHdltvinHandle.open("matrixmul.hdltvin.dat");
    mHdltvoutHandle.open("matrixmul.hdltvout.dat");
}

matrixmul::~matrixmul() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete matrixmul_mac_mulbkb_U1;
    delete matrixmul_mac_mulbkb_U2;
    delete matrixmul_mac_mulcud_U3;
    delete matrixmul_mac_mulcud_U4;
    delete matrixmul_mac_mulbkb_U5;
    delete matrixmul_mac_mulbkb_U6;
    delete matrixmul_mac_mulcud_U7;
    delete matrixmul_mac_mulcud_U8;
    delete matrixmul_mac_mulbkb_U9;
    delete matrixmul_mac_mulbkb_U10;
    delete matrixmul_mac_mulcud_U11;
    delete matrixmul_mac_mulcud_U12;
    delete matrixmul_mac_mulbkb_U13;
    delete matrixmul_mac_mulbkb_U14;
    delete matrixmul_mac_mulcud_U15;
    delete matrixmul_mac_mulcud_U16;
    delete matrixmul_mac_mulbkb_U17;
    delete matrixmul_mac_mulcud_U18;
}

void matrixmul::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
            ap_enable_reg_pp0_iter0_reg = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        add_ln60_10_reg_731 = grp_fu_500_p3.read();
        add_ln60_8_reg_726 = grp_fu_494_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0))) {
        add_ln60_12_reg_746 = grp_fu_518_p3.read();
        add_ln60_14_reg_751 = grp_fu_525_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        add_ln60_17_reg_756 = grp_fu_552_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        add_ln60_2_reg_623 = grp_fu_442_p3.read();
        add_ln60_reg_601 = grp_fu_434_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        add_ln60_4_reg_682 = grp_fu_466_p3.read();
        add_ln60_6_reg_699 = grp_fu_473_p3.read();
        tmp_11_reg_709 = a_q0.read().range(23, 16);
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        reg_252 = a_q0.read().range(15, 8);
        reg_256 = b_q0.read().range(15, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        sext_ln60_10_reg_714 = sext_ln60_10_fu_395_p1.read();
        sext_ln60_13_reg_720 = sext_ln60_13_fu_399_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        sext_ln60_11_reg_676 = sext_ln60_11_fu_371_p1.read();
        sext_ln60_12_reg_687 = sext_ln60_12_fu_380_p1.read();
        sext_ln60_14_reg_693 = sext_ln60_14_fu_383_p1.read();
        sext_ln60_2_reg_653 = sext_ln60_2_fu_352_p1.read();
        sext_ln60_3_reg_658 = sext_ln60_3_fu_356_p1.read();
        sext_ln60_7_reg_664 = sext_ln60_7_fu_360_p1.read();
        sext_ln60_9_reg_670 = sext_ln60_9_fu_367_p1.read();
        trunc_ln60_5_reg_704 = trunc_ln60_5_fu_391_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0))) {
        sext_ln60_15_reg_736 = sext_ln60_15_fu_410_p1.read();
        sext_ln60_17_reg_741 = sext_ln60_17_fu_413_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        sext_ln60_1_reg_584 = sext_ln60_1_fu_272_p1.read();
        sext_ln60_4_reg_590 = sext_ln60_4_fu_276_p1.read();
        sext_ln60_5_reg_595 = sext_ln60_5_fu_280_p1.read();
        sext_ln60_6_reg_606 = sext_ln60_6_fu_294_p1.read();
        sext_ln60_8_reg_617 = sext_ln60_8_fu_318_p1.read();
        sext_ln60_reg_579 = sext_ln60_fu_264_p1.read();
        tmp_6_reg_638 = a_q1.read().range(15, 8);
        tmp_7_reg_612 = b_q1.read().range(15, 8);
        tmp_9_reg_643 = a_q1.read().range(23, 16);
        trunc_ln60_4_reg_633 = trunc_ln60_4_fu_328_p1.read();
    }
}

void matrixmul::thread_a_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            a_address0 =  (sc_lv<2>) (ap_const_lv64_2);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            a_address0 =  (sc_lv<2>) (ap_const_lv64_0);
        } else {
            a_address0 = "XX";
        }
    } else {
        a_address0 = "XX";
    }
}

void matrixmul::thread_a_address1() {
    a_address1 =  (sc_lv<2>) (ap_const_lv64_1);
}

void matrixmul::thread_a_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void matrixmul::thread_a_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        a_ce1 = ap_const_logic_1;
    } else {
        a_ce1 = ap_const_logic_0;
    }
}

void matrixmul::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void matrixmul::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[1];
}

void matrixmul::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[2];
}

void matrixmul::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[3];
}

void matrixmul::thread_ap_CS_fsm_pp0_stage4() {
    ap_CS_fsm_pp0_stage4 = ap_CS_fsm.read()[4];
}

void matrixmul::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()));
}

void matrixmul::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()));
}

void matrixmul::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage4() {
    ap_block_pp0_stage4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage4_11001() {
    ap_block_pp0_stage4_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_pp0_stage4_subdone() {
    ap_block_pp0_stage4_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void matrixmul::thread_ap_block_state2_pp0_stage1_iter0() {
    ap_block_state2_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_state3_pp0_stage2_iter0() {
    ap_block_state3_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_state4_pp0_stage3_iter0() {
    ap_block_state4_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_state5_pp0_stage4_iter0() {
    ap_block_state5_pp0_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_block_state7_pp0_stage1_iter1() {
    ap_block_state7_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrixmul::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrixmul::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void matrixmul::thread_ap_enable_reg_pp0_iter0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
        ap_enable_reg_pp0_iter0 = ap_start.read();
    } else {
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg.read();
    }
}

void matrixmul::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrixmul::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void matrixmul::thread_ap_idle_pp0_0to0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read())) {
        ap_idle_pp0_0to0 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to0 = ap_const_logic_0;
    }
}

void matrixmul::thread_ap_idle_pp0_1to1() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read())) {
        ap_idle_pp0_1to1 = ap_const_logic_1;
    } else {
        ap_idle_pp0_1to1 = ap_const_logic_0;
    }
}

void matrixmul::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrixmul::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to0.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void matrixmul::thread_b_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            b_address0 =  (sc_lv<2>) (ap_const_lv64_2);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            b_address0 =  (sc_lv<2>) (ap_const_lv64_0);
        } else {
            b_address0 = "XX";
        }
    } else {
        b_address0 = "XX";
    }
}

void matrixmul::thread_b_address1() {
    b_address1 =  (sc_lv<2>) (ap_const_lv64_1);
}

void matrixmul::thread_b_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
        b_ce0 = ap_const_logic_1;
    } else {
        b_ce0 = ap_const_logic_0;
    }
}

void matrixmul::thread_b_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        b_ce1 = ap_const_logic_1;
    } else {
        b_ce1 = ap_const_logic_0;
    }
}

void matrixmul::thread_grp_fu_232_p4() {
    grp_fu_232_p4 = a_q0.read().range(23, 16);
}

void matrixmul::thread_grp_fu_242_p4() {
    grp_fu_242_p4 = b_q0.read().range(23, 16);
}

void matrixmul::thread_grp_fu_434_p1() {
    grp_fu_434_p1 =  (sc_lv<8>) (sext_ln60_fu_264_p1.read());
}

void matrixmul::thread_grp_fu_434_p2() {
    grp_fu_434_p2 = (!mul_ln60_2_fu_284_p0.read().is_01() || !mul_ln60_2_fu_284_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_2_fu_284_p0.read()) * sc_bigint<8>(mul_ln60_2_fu_284_p1.read());
}

void matrixmul::thread_grp_fu_442_p1() {
    grp_fu_442_p1 =  (sc_lv<8>) (sext_ln60_fu_264_p1.read());
}

void matrixmul::thread_grp_fu_442_p2() {
    grp_fu_442_p2 = (!mul_ln60_5_fu_322_p0.read().is_01() || !mul_ln60_5_fu_322_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_5_fu_322_p0.read()) * sc_bigint<8>(mul_ln60_5_fu_322_p1.read());
}

void matrixmul::thread_grp_fu_450_p1() {
    grp_fu_450_p1 =  (sc_lv<8>) (sext_ln60_2_fu_352_p1.read());
}

void matrixmul::thread_grp_fu_458_p1() {
    grp_fu_458_p1 =  (sc_lv<8>) (sext_ln60_2_fu_352_p1.read());
}

void matrixmul::thread_grp_fu_466_p1() {
    grp_fu_466_p1 =  (sc_lv<8>) (sext_ln60_reg_579.read());
}

void matrixmul::thread_grp_fu_466_p2() {
    grp_fu_466_p2 = (!mul_ln60_8_fu_375_p0.read().is_01() || !mul_ln60_8_fu_375_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_8_fu_375_p0.read()) * sc_bigint<8>(mul_ln60_8_fu_375_p1.read());
}

void matrixmul::thread_grp_fu_473_p0() {
    grp_fu_473_p0 =  (sc_lv<8>) (sext_ln60_1_reg_584.read());
}

void matrixmul::thread_grp_fu_473_p2() {
    grp_fu_473_p2 = (!mul_ln60_11_fu_386_p0.read().is_01() || !mul_ln60_11_fu_386_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_11_fu_386_p0.read()) * sc_bigint<8>(mul_ln60_11_fu_386_p1.read());
}

void matrixmul::thread_grp_fu_480_p1() {
    grp_fu_480_p1 =  (sc_lv<8>) (sext_ln60_2_reg_653.read());
}

void matrixmul::thread_grp_fu_487_p0() {
    grp_fu_487_p0 =  (sc_lv<8>) (sext_ln60_3_reg_658.read());
}

void matrixmul::thread_grp_fu_494_p0() {
    grp_fu_494_p0 =  (sc_lv<8>) (sext_ln60_6_reg_606.read());
}

void matrixmul::thread_grp_fu_494_p1() {
    grp_fu_494_p1 =  (sc_lv<8>) (sext_ln60_12_reg_687.read());
}

void matrixmul::thread_grp_fu_494_p2() {
    grp_fu_494_p2 = (!mul_ln60_14_fu_402_p0.read().is_01() || !mul_ln60_14_fu_402_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_14_fu_402_p0.read()) * sc_bigint<8>(mul_ln60_14_fu_402_p1.read());
}

void matrixmul::thread_grp_fu_500_p0() {
    grp_fu_500_p0 =  (sc_lv<8>) (sext_ln60_9_reg_670.read());
}

void matrixmul::thread_grp_fu_500_p1() {
    grp_fu_500_p1 =  (sc_lv<8>) (sext_ln60_12_reg_687.read());
}

void matrixmul::thread_grp_fu_500_p2() {
    grp_fu_500_p2 = (!mul_ln60_17_fu_406_p0.read().is_01() || !mul_ln60_17_fu_406_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_17_fu_406_p0.read()) * sc_bigint<8>(mul_ln60_17_fu_406_p1.read());
}

void matrixmul::thread_grp_fu_506_p0() {
    grp_fu_506_p0 =  (sc_lv<8>) (sext_ln60_7_reg_664.read());
}

void matrixmul::thread_grp_fu_506_p1() {
    grp_fu_506_p1 =  (sc_lv<8>) (sext_ln60_13_reg_720.read());
}

void matrixmul::thread_grp_fu_512_p0() {
    grp_fu_512_p0 =  (sc_lv<8>) (sext_ln60_10_reg_714.read());
}

void matrixmul::thread_grp_fu_512_p1() {
    grp_fu_512_p1 =  (sc_lv<8>) (sext_ln60_13_reg_720.read());
}

void matrixmul::thread_grp_fu_518_p0() {
    grp_fu_518_p0 =  (sc_lv<8>) (sext_ln60_1_reg_584.read());
}

void matrixmul::thread_grp_fu_518_p1() {
    grp_fu_518_p1 =  (sc_lv<8>) (sext_ln60_15_fu_410_p1.read());
}

void matrixmul::thread_grp_fu_518_p2() {
    grp_fu_518_p2 = (!mul_ln60_20_fu_416_p0.read().is_01() || !mul_ln60_20_fu_416_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_20_fu_416_p0.read()) * sc_bigint<8>(mul_ln60_20_fu_416_p1.read());
}

void matrixmul::thread_grp_fu_525_p0() {
    grp_fu_525_p0 =  (sc_lv<8>) (sext_ln60_6_reg_606.read());
}

void matrixmul::thread_grp_fu_525_p1() {
    grp_fu_525_p1 =  (sc_lv<8>) (sext_ln60_15_fu_410_p1.read());
}

void matrixmul::thread_grp_fu_525_p2() {
    grp_fu_525_p2 = (!mul_ln60_23_fu_421_p0.read().is_01() || !mul_ln60_23_fu_421_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_23_fu_421_p0.read()) * sc_bigint<8>(mul_ln60_23_fu_421_p1.read());
}

void matrixmul::thread_grp_fu_532_p0() {
    grp_fu_532_p0 =  (sc_lv<8>) (sext_ln60_3_reg_658.read());
}

void matrixmul::thread_grp_fu_532_p1() {
    grp_fu_532_p1 =  (sc_lv<8>) (sext_ln60_16_fu_426_p1.read());
}

void matrixmul::thread_grp_fu_539_p0() {
    grp_fu_539_p0 =  (sc_lv<8>) (sext_ln60_7_reg_664.read());
}

void matrixmul::thread_grp_fu_539_p1() {
    grp_fu_539_p1 =  (sc_lv<8>) (sext_ln60_16_fu_426_p1.read());
}

void matrixmul::thread_grp_fu_546_p0() {
    grp_fu_546_p0 =  (sc_lv<8>) (sext_ln60_9_reg_670.read());
}

void matrixmul::thread_grp_fu_546_p1() {
    grp_fu_546_p1 =  (sc_lv<8>) (sext_ln60_15_reg_736.read());
}

void matrixmul::thread_grp_fu_546_p2() {
    grp_fu_546_p2 = (!mul_ln60_26_fu_430_p0.read().is_01() || !mul_ln60_26_fu_430_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln60_26_fu_430_p0.read()) * sc_bigint<8>(mul_ln60_26_fu_430_p1.read());
}

void matrixmul::thread_grp_fu_552_p0() {
    grp_fu_552_p0 =  (sc_lv<8>) (sext_ln60_10_reg_714.read());
}

void matrixmul::thread_grp_fu_552_p1() {
    grp_fu_552_p1 =  (sc_lv<8>) (sext_ln60_16_fu_426_p1.read());
}

void matrixmul::thread_mul_ln60_11_fu_386_p0() {
    mul_ln60_11_fu_386_p0 =  (sc_lv<8>) (sext_ln60_5_reg_595.read());
}

void matrixmul::thread_mul_ln60_11_fu_386_p1() {
    mul_ln60_11_fu_386_p1 = tmp_9_reg_643.read();
}

void matrixmul::thread_mul_ln60_14_fu_402_p0() {
    mul_ln60_14_fu_402_p0 =  (sc_lv<8>) (sext_ln60_8_reg_617.read());
}

void matrixmul::thread_mul_ln60_14_fu_402_p1() {
    mul_ln60_14_fu_402_p1 =  (sc_lv<8>) (sext_ln60_14_reg_693.read());
}

void matrixmul::thread_mul_ln60_17_fu_406_p0() {
    mul_ln60_17_fu_406_p0 =  (sc_lv<8>) (sext_ln60_11_reg_676.read());
}

void matrixmul::thread_mul_ln60_17_fu_406_p1() {
    mul_ln60_17_fu_406_p1 =  (sc_lv<8>) (sext_ln60_14_reg_693.read());
}

void matrixmul::thread_mul_ln60_20_fu_416_p0() {
    mul_ln60_20_fu_416_p0 =  (sc_lv<8>) (sext_ln60_5_reg_595.read());
}

void matrixmul::thread_mul_ln60_20_fu_416_p1() {
    mul_ln60_20_fu_416_p1 =  (sc_lv<8>) (sext_ln60_17_fu_413_p1.read());
}

void matrixmul::thread_mul_ln60_23_fu_421_p0() {
    mul_ln60_23_fu_421_p0 =  (sc_lv<8>) (sext_ln60_8_reg_617.read());
}

void matrixmul::thread_mul_ln60_23_fu_421_p1() {
    mul_ln60_23_fu_421_p1 =  (sc_lv<8>) (sext_ln60_17_fu_413_p1.read());
}

void matrixmul::thread_mul_ln60_26_fu_430_p0() {
    mul_ln60_26_fu_430_p0 =  (sc_lv<8>) (sext_ln60_11_reg_676.read());
}

void matrixmul::thread_mul_ln60_26_fu_430_p1() {
    mul_ln60_26_fu_430_p1 =  (sc_lv<8>) (sext_ln60_17_reg_741.read());
}

void matrixmul::thread_mul_ln60_2_fu_284_p0() {
    mul_ln60_2_fu_284_p0 = grp_fu_242_p4.read();
}

void matrixmul::thread_mul_ln60_2_fu_284_p1() {
    mul_ln60_2_fu_284_p1 =  (sc_lv<8>) (sext_ln60_4_fu_276_p1.read());
}

void matrixmul::thread_mul_ln60_5_fu_322_p0() {
    mul_ln60_5_fu_322_p0 = tmp_8_fu_308_p4.read();
}

void matrixmul::thread_mul_ln60_5_fu_322_p1() {
    mul_ln60_5_fu_322_p1 =  (sc_lv<8>) (sext_ln60_4_fu_276_p1.read());
}

void matrixmul::thread_mul_ln60_8_fu_375_p0() {
    mul_ln60_8_fu_375_p0 = grp_fu_242_p4.read();
}

void matrixmul::thread_mul_ln60_8_fu_375_p1() {
    mul_ln60_8_fu_375_p1 =  (sc_lv<8>) (sext_ln60_4_reg_590.read());
}

void matrixmul::thread_res_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        res_address0 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
        res_address0 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        res_address0 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        res_address0 =  (sc_lv<4>) (ap_const_lv64_1);
    } else {
        res_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void matrixmul::thread_res_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_address1 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
        res_address1 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        res_address1 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        res_address1 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        res_address1 =  (sc_lv<4>) ("XXXX");
    }
}

void matrixmul::thread_res_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        res_ce0 = ap_const_logic_1;
    } else {
        res_ce0 = ap_const_logic_0;
    }
}

void matrixmul::thread_res_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        res_ce1 = ap_const_logic_1;
    } else {
        res_ce1 = ap_const_logic_0;
    }
}

void matrixmul::thread_res_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        res_d0 = add_ln60_17_reg_756.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_d0 = grp_fu_532_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
        res_d0 = grp_fu_512_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        res_d0 = grp_fu_487_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        res_d0 = grp_fu_458_p3.read();
    } else {
        res_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void matrixmul::thread_res_d1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        res_d1 = grp_fu_539_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
        res_d1 = grp_fu_506_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        res_d1 = grp_fu_480_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        res_d1 = grp_fu_450_p3.read();
    } else {
        res_d1 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void matrixmul::thread_res_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        res_we0 = ap_const_logic_1;
    } else {
        res_we0 = ap_const_logic_0;
    }
}

void matrixmul::thread_res_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        res_we1 = ap_const_logic_1;
    } else {
        res_we1 = ap_const_logic_0;
    }
}

void matrixmul::thread_sext_ln60_10_fu_395_p1() {
    sext_ln60_10_fu_395_p1 = esl_sext<16,8>(reg_256.read());
}

void matrixmul::thread_sext_ln60_11_fu_371_p1() {
    sext_ln60_11_fu_371_p1 = esl_sext<16,8>(grp_fu_242_p4.read());
}

void matrixmul::thread_sext_ln60_12_fu_380_p1() {
    sext_ln60_12_fu_380_p1 = esl_sext<16,8>(trunc_ln60_4_reg_633.read());
}

void matrixmul::thread_sext_ln60_13_fu_399_p1() {
    sext_ln60_13_fu_399_p1 = esl_sext<16,8>(tmp_6_reg_638.read());
}

void matrixmul::thread_sext_ln60_14_fu_383_p1() {
    sext_ln60_14_fu_383_p1 = esl_sext<16,8>(tmp_9_reg_643.read());
}

void matrixmul::thread_sext_ln60_15_fu_410_p1() {
    sext_ln60_15_fu_410_p1 = esl_sext<16,8>(trunc_ln60_5_reg_704.read());
}

void matrixmul::thread_sext_ln60_16_fu_426_p1() {
    sext_ln60_16_fu_426_p1 = esl_sext<16,8>(reg_252.read());
}

void matrixmul::thread_sext_ln60_17_fu_413_p1() {
    sext_ln60_17_fu_413_p1 = esl_sext<16,8>(tmp_11_reg_709.read());
}

void matrixmul::thread_sext_ln60_1_fu_272_p1() {
    sext_ln60_1_fu_272_p1 = esl_sext<16,8>(trunc_ln60_1_fu_268_p1.read());
}

void matrixmul::thread_sext_ln60_2_fu_352_p1() {
    sext_ln60_2_fu_352_p1 = esl_sext<16,8>(reg_252.read());
}

void matrixmul::thread_sext_ln60_3_fu_356_p1() {
    sext_ln60_3_fu_356_p1 = esl_sext<16,8>(reg_256.read());
}

void matrixmul::thread_sext_ln60_4_fu_276_p1() {
    sext_ln60_4_fu_276_p1 = esl_sext<16,8>(grp_fu_232_p4.read());
}

void matrixmul::thread_sext_ln60_5_fu_280_p1() {
    sext_ln60_5_fu_280_p1 = esl_sext<16,8>(grp_fu_242_p4.read());
}

void matrixmul::thread_sext_ln60_6_fu_294_p1() {
    sext_ln60_6_fu_294_p1 = esl_sext<16,8>(trunc_ln60_2_fu_290_p1.read());
}

void matrixmul::thread_sext_ln60_7_fu_360_p1() {
    sext_ln60_7_fu_360_p1 = esl_sext<16,8>(tmp_7_reg_612.read());
}

void matrixmul::thread_sext_ln60_8_fu_318_p1() {
    sext_ln60_8_fu_318_p1 = esl_sext<16,8>(tmp_8_fu_308_p4.read());
}

void matrixmul::thread_sext_ln60_9_fu_367_p1() {
    sext_ln60_9_fu_367_p1 = esl_sext<16,8>(trunc_ln60_3_fu_363_p1.read());
}

void matrixmul::thread_sext_ln60_fu_264_p1() {
    sext_ln60_fu_264_p1 = esl_sext<16,8>(trunc_ln60_fu_260_p1.read());
}

void matrixmul::thread_tmp_8_fu_308_p4() {
    tmp_8_fu_308_p4 = b_q1.read().range(23, 16);
}

void matrixmul::thread_trunc_ln60_1_fu_268_p1() {
    trunc_ln60_1_fu_268_p1 = b_q0.read().range(8-1, 0);
}

void matrixmul::thread_trunc_ln60_2_fu_290_p1() {
    trunc_ln60_2_fu_290_p1 = b_q1.read().range(8-1, 0);
}

void matrixmul::thread_trunc_ln60_3_fu_363_p1() {
    trunc_ln60_3_fu_363_p1 = b_q0.read().range(8-1, 0);
}

void matrixmul::thread_trunc_ln60_4_fu_328_p1() {
    trunc_ln60_4_fu_328_p1 = a_q1.read().range(8-1, 0);
}

void matrixmul::thread_trunc_ln60_5_fu_391_p1() {
    trunc_ln60_5_fu_391_p1 = a_q0.read().range(8-1, 0);
}

void matrixmul::thread_trunc_ln60_fu_260_p1() {
    trunc_ln60_fu_260_p1 = a_q0.read().range(8-1, 0);
}

void matrixmul::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_1to1.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reset_idle_pp0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reset_idle_pp0.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

void matrixmul::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_address0\" :  \"" << a_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_ce0\" :  \"" << a_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a_q0\" :  \"" << a_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_address1\" :  \"" << a_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_ce1\" :  \"" << a_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a_q1\" :  \"" << a_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_address0\" :  \"" << b_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_ce0\" :  \"" << b_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_q0\" :  \"" << b_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_address1\" :  \"" << b_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_ce1\" :  \"" << b_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_q1\" :  \"" << b_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_address0\" :  \"" << res_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_ce0\" :  \"" << res_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_we0\" :  \"" << res_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_d0\" :  \"" << res_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_address1\" :  \"" << res_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_ce1\" :  \"" << res_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_we1\" :  \"" << res_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_d1\" :  \"" << res_d1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

